name: Run Journey Tests on GitHub

inputs:
  marine-licensing-backend:
    required: false
    type: string
  marine-licensing-frontend:
    required: false
    type: string
  branch:
    required: false
    type: string
    default: main

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/marine-licensing-journey-tests
        path: ./marine-licensing-journey-tests

    - name: Extract dependent Pull Requests
      uses: depends-on/depends-on-action@0.15.0
      with:
        token: ${{ github.token }}
        path: ./marine-licensing-journey-tests

    - name: Determine journey-tests branch
      if: github.repository != 'DEFRA/marine-licensing-journey-tests'
      id: resolve_tests_branch
      shell: bash
      run: |
        set -e

        DEFAULT_BRANCH="${{ inputs.branch }}"
        BRANCH_TO_USE="$DEFAULT_BRANCH"

        DEPENDS_FILE='./marine-licensing-journey-tests/depends-on.json'
        ROOT_DEPENDS_FILE='./depends-on.json'

        resolve_branch_from_depends() {
          local file="$1"
          local branch=""

          branch=$(jq -r '.dependencies[]? | select(.repo == "DEFRA/marine-licensing-journey-tests") | .ref // empty' "$file" 2>/dev/null | head -1)

          if [ -z "$branch" ]; then
            local description
            description=$(jq -r '.description // empty' "$file" 2>/dev/null)
            if [ -n "$description" ]; then
              local depends_lines
              depends_lines=$(printf '%s\n' "$description" | grep -iE '^\s*depends[- ]?on[: ]+' || true)

              if [ -n "$depends_lines" ] && ! printf '%s\n' "$depends_lines" | grep -qiE 'https://github.com/.*/pull/[0-9]+'; then
                local invalid_placeholder
                invalid_placeholder=$(printf '%s\n' "$depends_lines" | sed -nE 's/.*(<[^>]*-pr-link>).*/\1/p' | head -1)

                if [ -z "$invalid_placeholder" ]; then
                  invalid_placeholder='<pr-link>'
                fi

                >&2 echo "ValueError: Invalid URL $invalid_placeholder"
                exit 1
              fi

              local dep_line
              dep_line=$(printf '%s\n' "${depends_lines:-$description}" | grep -iE 'depends[- ]?on[: ]+.*marine-licensing-journey-tests' | head -1 || true)
              if [ -n "$dep_line" ]; then
                local candidate
                candidate=$(printf '%s\n' "$dep_line" | sed -E 's#^.*marine-licensing-journey-tests[@:]+([A-Za-z0-9._/\-]+).*$#\1#I')
                if [ -n "$candidate" ] && [ "$candidate" != "$dep_line" ]; then
                  branch="$candidate"
                else
                  local pr_num
                  pr_num=$(printf '%s\n' "$dep_line" | sed -nE 's#.*marine-licensing-journey-tests.*/pull/([0-9]+).*#\1#p')
                  if [ -z "$pr_num" ]; then
                    pr_num=$(printf '%s\n' "$dep_line" | sed -nE 's#.*marine-licensing-journey-tests[^0-9]*([0-9]+).*#\1#p')
                  fi
                  if [ -n "$pr_num" ]; then
                    >&2 echo "ℹ️  Resolving PR #$pr_num head branch for marine-licensing-journey-tests"
                    local api_headers=("-H" "Accept: application/vnd.github+json")
                    if [ -n "$GITHUB_TOKEN" ]; then
                      api_headers+=("-H" "Authorization: Bearer $GITHUB_TOKEN")
                    fi
                    branch=$(curl -sS "https://api.github.com/repos/DEFRA/marine-licensing-journey-tests/pulls/$pr_num" "${api_headers[@]}" | jq -r '.head.ref // empty')
                  fi
                fi
              fi
            fi
          fi

          printf '%s' "$branch"
        }

        BRANCH_FROM_DEPENDS=""

        if [ -f "$DEPENDS_FILE" ]; then
          BRANCH_FROM_DEPENDS="$(resolve_branch_from_depends "$DEPENDS_FILE")"
          if [ -z "$BRANCH_FROM_DEPENDS" ]; then
            echo "ℹ️ depends-on.json did not contain an entry for DEFRA/marine-licensing-journey-tests"
          fi
        elif [ -f "$ROOT_DEPENDS_FILE" ]; then
          BRANCH_FROM_DEPENDS="$(resolve_branch_from_depends "$ROOT_DEPENDS_FILE")"
          if [ -z "$BRANCH_FROM_DEPENDS" ]; then
            echo "ℹ️ depends-on.json (root) did not contain an entry for DEFRA/marine-licensing-journey-tests"
          fi
        else
          echo "ℹ️ No depends-on.json found; using default branch $DEFAULT_BRANCH"
        fi

        if [ -n "$BRANCH_FROM_DEPENDS" ]; then
          if git ls-remote --exit-code --heads https://github.com/DEFRA/marine-licensing-journey-tests.git "$BRANCH_FROM_DEPENDS" >/dev/null 2>&1; then
            echo "✅ Using depends-on branch from depends-on action: $BRANCH_FROM_DEPENDS"
            BRANCH_TO_USE="$BRANCH_FROM_DEPENDS"
            echo "branch_discovered_source=depends-on-json" >> "$GITHUB_OUTPUT"
          else
            echo "⚠️ Branch '$BRANCH_FROM_DEPENDS' from depends-on.json not found on remote; retaining default: $DEFAULT_BRANCH"
          fi
        fi

        echo "branch=$BRANCH_TO_USE" >> "$GITHUB_OUTPUT"
        echo "📦 Selected journey-tests branch: $BRANCH_TO_USE"

    - name: Alternative checkout attempt (only if called from different repo)
      if: github.repository != 'DEFRA/marine-licensing-journey-tests'
      run: |
        set -e
        rm -rf ./marine-licensing-journey-tests

        BRANCH_TO_USE='${{ steps.resolve_tests_branch.outputs.branch }}'
        DEFAULT_BRANCH='${{ inputs.branch }}'

        echo "Cloning marine-licensing-journey-tests branch: $BRANCH_TO_USE"
        git clone --branch "$BRANCH_TO_USE" --depth 1 https://github.com/DEFRA/marine-licensing-journey-tests.git ./marine-licensing-journey-tests || {
          echo "Falling back to default branch: $DEFAULT_BRANCH"
          git clone --branch "$DEFAULT_BRANCH" --depth 1 https://github.com/DEFRA/marine-licensing-journey-tests.git ./marine-licensing-journey-tests
        }

      shell: bash

    - name: Build marine-licensing-frontend image
      run: |
        echo "=== Building Frontend Image ==="
        echo "Current directory: $(pwd)"

        if [ -d "../../marine-licensing-frontend" ]; then
          echo "✅ Found frontend directory - building PR image"
          cd ../../marine-licensing-frontend
          echo "Branch: $(git branch --show-current) | Commit: $(git log -1 --oneline)"
          docker build -t defradigital/marine-licensing-frontend:pr-build .
          echo "✅ Frontend PR image built successfully"
        else
          echo "ℹ️  No frontend directory found - will use latest image"
          echo "This is normal if no frontend dependency was specified in PR description"
        fi
      shell: bash
      working-directory: ./marine-licensing-journey-tests

    - name: Build marine-licensing-backend image
      run: |
        echo "=== Building Backend Image ==="
        echo "Current directory: $(pwd)"

        if [ -d "../../marine-licensing-backend" ]; then
          echo "✅ Found backend directory - building PR image"
          cd ../../marine-licensing-backend
          echo "Branch: $(git branch --show-current) | Commit: $(git log -1 --oneline)"
          docker build -t defradigital/marine-licensing-backend:pr-build .
          echo "✅ Backend PR image built successfully"
        else
          echo "ℹ️  No backend directory found - will use latest image"
          echo "This is normal if no backend dependency was specified in PR description"
        fi
      shell: bash
      working-directory: ./marine-licensing-journey-tests

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: ./marine-licensing-journey-tests/package-lock.json

    - name: Setup the tests
      run: |
        npm ci
        npx playwright install chromium --with-deps
      shell: bash
      working-directory: ./marine-licensing-journey-tests

    - name: Start docker compose
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        # Priority: PR images > specified inputs > latest
        # Check if we built PR images and use them if available
        if docker image inspect defradigital/marine-licensing-frontend:pr-build >/dev/null 2>&1; then
          echo "✅ Using PR-built frontend image (from depends-on)"
          FRONTEND_VERSION="pr-build"
        else
          FRONTEND_VERSION="${{ inputs.marine-licensing-frontend }}"
          echo "ℹ️  Using frontend version: ${FRONTEND_VERSION:-latest} (no PR dependency)"
        fi

        if docker image inspect defradigital/marine-licensing-backend:pr-build >/dev/null 2>&1; then
          echo "✅ Using PR-built backend image (from depends-on)"
          BACKEND_VERSION="pr-build"
        else
          BACKEND_VERSION="${{ inputs.marine-licensing-backend }}"
          echo "ℹ️  Using backend version: ${BACKEND_VERSION:-latest} (no PR dependency)"
        fi

        echo "🐳 Starting containers with:"
        echo "  Frontend: ${FRONTEND_VERSION:-latest}"
        echo "  Backend: ${BACKEND_VERSION:-latest}"

        MARINE_LICENSING_FRONTEND_VERSION=${FRONTEND_VERSION:-latest} \
        MARINE_LICENSING_BACKEND_VERSION=${BACKEND_VERSION:-latest} \
        docker compose -f $(pwd)/compose.common.yml up --wait-timeout 300 -d --quiet-pull

    - name: Check initial service status
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        echo "=== Initial Docker Compose Status ==="
        docker compose -f $(pwd)/compose.common.yml ps
        echo "=== Service Logs (first 20 lines) ==="
        docker compose -f $(pwd)/compose.common.yml logs --tail=20 || echo "No logs available yet"

    - name: Wait for services to be ready
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        echo "Waiting for backend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'
        echo "Waiting for Defra ID stub to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:3200/health; do sleep 5; done'
        echo "Waiting for frontend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3000/health; do sleep 5; done'
        echo "All services are ready!"

    - name: Check service status
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        echo "=== Docker Compose Status ==="
        docker compose -f $(pwd)/compose.common.yml ps
        echo "=== Testing Service Connectivity ==="
        echo "Testing from runner to frontend..."
        curl --fail --silent --connect-timeout 5 http://localhost:3000/health || (echo "❌ Cannot reach frontend from runner!" && exit 1)
        echo "Testing from runner to defra-id-stub..."
        curl --fail --silent --connect-timeout 5 http://localhost:3200/health || (echo "❌ Cannot reach defra-id-stub from runner!" && exit 1)
        echo "Testing defra-id-stub API endpoint..."
        curl -v --connect-timeout 5 http://localhost:3200/cdp-defra-id-stub/API/register -X POST -H "Content-Type: application/json" -d '{"email":"test@example.com","password":"TestPassword123!","firstName":"Test","lastName":"User"}' || echo "Defra ID stub API test completed (may show expected errors)"
        echo "All connectivity checks passed!"

    - name: Run the tests
      id: run-tests
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      env:
        DEFRA_ID_URL: http://localhost:3200
      run: |
        echo "=== Running Playwright tests ==="
        npm run test:pw:github

    - name: debug
      if: always()
      working-directory: ./marine-licensing-journey-tests
      run: |
        docker compose -f $(pwd)/compose.common.yml logs > logs.txt
        docker ps
      shell: bash

    - name: Generate Allure report
      if: always()
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        echo "=== Generating Allure Report ==="
        npm run report:pw

    - name: Parse test results
      if: always() && github.event_name == 'pull_request'
      id: test-results
      shell: bash
      working-directory: ./marine-licensing-journey-tests
      run: |
        if [ ! -f "cucumber-results.json" ]; then
          echo "total=0" >> $GITHUB_OUTPUT
          echo "passed=0" >> $GITHUB_OUTPUT
          echo "failed=0" >> $GITHUB_OUTPUT
          echo "pending=0" >> $GITHUB_OUTPUT
          echo "status_emoji=⚠️" >> $GITHUB_OUTPUT
          echo "status_text=No test results found" >> $GITHUB_OUTPUT
          echo "pass_rate=0" >> $GITHUB_OUTPUT
          exit 0
        fi

        TOTAL=$(jq '[.[].elements[]] | length' cucumber-results.json)
        PASSED=$(jq '[.[].elements[] | select(.steps | all(.result.status == "passed"))] | length' cucumber-results.json)
        FAILED=$(jq '[.[].elements[] | select(.steps | any(.result.status == "failed"))] | length' cucumber-results.json)
        PENDING=$(jq '[.[].elements[] | select(.steps | any(.result.status == "undefined" or .result.status == "pending"))] | length' cucumber-results.json)

        if [ $TOTAL -gt 0 ]; then
          PASS_RATE=$((PASSED * 100 / TOTAL))
        else
          PASS_RATE=0
        fi

        if [ $FAILED -eq 0 ] && [ $TOTAL -gt 0 ]; then
          STATUS_EMOJI="✅"
          STATUS_TEXT="All tests passed"
        elif [ $TOTAL -eq 0 ]; then
          STATUS_EMOJI="⚠️"
          STATUS_TEXT="No tests were executed"
        else
          STATUS_EMOJI="❌"
          STATUS_TEXT="Test failures detected"
        fi

        echo "=== Test Results Summary ==="
        echo "TOTAL=$TOTAL, PASSED=$PASSED, FAILED=$FAILED, PENDING=$PENDING"
        echo "PASS_RATE=$PASS_RATE%, STATUS=$STATUS_TEXT"

        echo "total=$TOTAL" >> $GITHUB_OUTPUT
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "failed=$FAILED" >> $GITHUB_OUTPUT
        echo "pending=$PENDING" >> $GITHUB_OUTPUT
        echo "pass_rate=$PASS_RATE" >> $GITHUB_OUTPUT
        echo "status_emoji=$STATUS_EMOJI" >> $GITHUB_OUTPUT
        echo "status_text=$STATUS_TEXT" >> $GITHUB_OUTPUT

    - name: Find existing comment
      if: always() && github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Marine Licensing Journey Tests

    - name: Create or update PR comment with test results
      if: always() && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          ## Marine Licensing Journey Tests

          ### ${{ steps.test-results.outputs.status_emoji || '⚠️' }} ${{ steps.test-results.outputs.status_text || 'Test Results' }}

          | Metric | Count |
          |:-------|------:|
          | **Total Scenarios** | ${{ steps.test-results.outputs.total || '0' }} |
          | **Passed** | ${{ steps.test-results.outputs.passed || '0' }} |
          | **Failed** | ${{ steps.test-results.outputs.failed || '0' }} |
          | **Pending** | ${{ steps.test-results.outputs.pending || '0' }} |
          | **Pass Rate** | ${{ steps.test-results.outputs.pass_rate || '0' }}% |

          ---

          **[View Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./marine-licensing-journey-tests/allure-results/
        retention-days: 30

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./marine-licensing-journey-tests/allure-report/index.html
        retention-days: 30

    - name: Upload Cucumber report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: |
          ./marine-licensing-journey-tests/cucumber-report.html
          ./marine-licensing-journey-tests/cucumber-results.json
        retention-days: 30

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./marine-licensing-journey-tests/logs.txt
        retention-days: 30

    - name: Check test results
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.run-tests.outcome }}" == "failure" ]; then
          echo "Tests failed"
          exit 1
        fi
