name: Run Journey Tests on GitHub

inputs:
  marine-licensing-backend:
    required: false
    type: string
  marine-licensing-frontend:
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/marine-licensing-journey-tests

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash
    - name: Start docker compose
      shell: bash
      run: |
        MARINE_LICENSING_FRONTEND=${{inputs.marine-licensing-frontend}} \
        MARINE_LICENSING_BACKEND=${{inputs.marine-licensing-backend}} \
        docker compose up -f compose.common.yml --wait-timeout 300 -d --quiet-pull
    - name: Run the tests
      shell: bash
      run: |
        npm run test:github
        npm run report
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
