name: Run Journey Tests on GitHub

inputs:
  marine-licensing-backend:
    required: false
    type: string
  marine-licensing-frontend:
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/marine-licensing-journey-tests

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Setup the tests
      run: npm i
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
        MARINE_LICENSING_FRONTEND_VERSION=${{inputs.marine-licensing-frontend}} \
        MARINE_LICENSING_BACKEND_VERSION=${{inputs.marine-licensing-backend}} \
        docker compose -f compose.common.yml up --wait-timeout 300 -d --quiet-pull

    - name: Check initial service status
      shell: bash
      run: |
        echo "=== Initial Docker Compose Status ==="
        docker compose -f compose.common.yml ps
        echo "=== Service Logs (first 20 lines) ==="
        docker compose -f compose.common.yml logs --tail=20 || echo "No logs available yet"

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for selenium-chrome to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:4444/wd/hub/status; do sleep 5; done'
        echo "Waiting for backend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'
        echo "Waiting for Defra ID stub to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:3200/health; do sleep 5; done'
        echo "Waiting for frontend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3000/health; do sleep 5; done'
        echo "All services are ready!"

    - name: Check service status
      shell: bash
      run: |
        echo "=== Docker Compose Status ==="
        docker compose -f compose.common.yml ps
        echo "=== Testing Frontend Connectivity ==="
        echo "Testing from runner to frontend..."
        curl --fail --silent --connect-timeout 5 http://localhost:3000/health || (echo "❌ Cannot reach frontend from runner!" && exit 1)
        echo "Testing from selenium container to frontend..."
        docker compose -f compose.common.yml exec -T selenium-chrome curl --fail --silent --connect-timeout 5 http://marine-licensing-frontend:3000/health || (echo "❌ Cannot reach frontend from selenium container!" && exit 1)
        echo "Testing from selenium container to defra-id-stub..."
        docker compose -f compose.common.yml exec -T selenium-chrome curl --fail --silent --connect-timeout 5 http://defra-id-stub:3200/health || (echo "❌ Cannot reach defra-id-stub from selenium container!" && exit 1)

    - name: Run the tests
      shell: bash
      env:
        CHROMEDRIVER_URL: localhost
        # Use local infrastructure endpoints
      run: |
        echo "=== Cleaning previous results ==="
        rm -rf allure-results allure-report
        echo "=== Running tests ==="
        npm run test:github
        echo "=== Checking test results ==="
        ls -la allure-results/ || echo "No allure-results directory found"

    - name: debug
      if: always()
      run: |
        docker compose -f compose.common.yml logs > logs.txt
        docker ps
      shell: bash

    - name: Generate Allure report
      if: always()
      shell: bash
      run: |
        npm run report:github

    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report/index.html # Single HTML file (not folder structure)

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
